name = "Iridius Modpack"
author = "mathgeniuszach"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb21df27080e4291c812d7213c0daa7f0b4b1e5cb65293cdd2571eaec79cc328"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
acceptable-game-versions = []
