name = "Iridius Modpack"
author = "mathgeniuszach"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c34edf330a438c24c04f1326225f648f6d40c773092712529bf1f94f5061a09"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
acceptable-game-versions = []
